import type { Playlist, Video } from '../types';

export const seedVideos: Record<string, Video> = {
  // — Tech Talks playlist
  'v-tech-01': {
    id: 'v-tech-01',
    url: 'https://www.youtube.com/watch?v=dQw4w9WgXcQ',
    title: 'React 19 — Ce qui change vraiment',
    thumbnail: 'https://img.youtube.com/vi/dQw4w9WgXcQ/hqdefault.jpg',
    duration: 1847,
    source: 'youtube',
    addedAt: '2026-03-01T10:00:00.000Z',
    isFavorite: true,
  },
  'v-tech-02': {
    id: 'v-tech-02',
    url: 'https://www.youtube.com/watch?v=BcVRqMB7Z6A',
    title: 'Zustand vs Redux — Comparaison complète',
    thumbnail: 'https://img.youtube.com/vi/BcVRqMB7Z6A/hqdefault.jpg',
    duration: 2134,
    source: 'youtube',
    addedAt: '2026-03-02T14:30:00.000Z',
    isFavorite: false,
  },
  'v-tech-03': {
    id: 'v-tech-03',
    url: 'https://www.youtube.com/watch?v=N3AkSS5hXMA',
    title: 'TypeScript 5 — Nouveautés et patterns avancés',
    thumbnail: 'https://img.youtube.com/vi/N3AkSS5hXMA/hqdefault.jpg',
    duration: 3210,
    source: 'youtube',
    addedAt: '2026-03-05T09:00:00.000Z',
    isFavorite: true,
  },
  'v-tech-04': {
    id: 'v-tech-04',
    url: 'https://vimeo.com/76979871',
    title: 'The Art of Code — Talk conférence JSConf',
    thumbnail: 'https://i.vimeocdn.com/video/452001751_640.jpg',
    duration: 2580,
    source: 'vimeo',
    addedAt: '2026-03-07T16:00:00.000Z',
    isFavorite: false,
  },
  'v-tech-05': {
    id: 'v-tech-05',
    url: 'https://www.youtube.com/watch?v=8pDqJVdNa44',
    title: 'Expo Router v3 — Navigation file-based',
    thumbnail: 'https://img.youtube.com/vi/8pDqJVdNa44/hqdefault.jpg',
    duration: 1560,
    source: 'youtube',
    addedAt: '2026-03-10T11:00:00.000Z',
    isFavorite: false,
  },

  // — Nature & Voyages playlist
  'v-nature-01': {
    id: 'v-nature-01',
    url: 'https://vimeo.com/channels/staffpicks/161482071',
    title: 'Iceland — Terre de feu et de glace',
    thumbnail: 'https://i.vimeocdn.com/video/560965144_640.jpg',
    duration: 486,
    source: 'vimeo',
    addedAt: '2026-03-03T08:00:00.000Z',
    isFavorite: true,
  },
  'v-nature-02': {
    id: 'v-nature-02',
    url: 'https://www.dailymotion.com/video/x7tgad0',
    title: 'Amazonie — Au cœur de la forêt primaire',
    thumbnail: 'https://s2.dmcdn.net/v/Sp3ix1Y4Ukg3J7A2F/x720',
    duration: 1800,
    source: 'dailymotion',
    addedAt: '2026-03-04T12:00:00.000Z',
    isFavorite: false,
  },
  'v-nature-03': {
    id: 'v-nature-03',
    url: 'https://vimeo.com/174401759',
    title: 'Patagonie — Drone au bout du monde',
    thumbnail: 'https://i.vimeocdn.com/video/583280279_640.jpg',
    duration: 312,
    source: 'vimeo',
    addedAt: '2026-03-06T15:00:00.000Z',
    isFavorite: true,
  },
  'v-nature-04': {
    id: 'v-nature-04',
    url: 'https://www.dailymotion.com/video/x6y8ttl',
    title: 'Sahara — Caravane au lever du soleil',
    thumbnail: 'https://s2.dmcdn.net/v/Sq8ij1Y4Whg3J7A2F/x720',
    duration: 2220,
    source: 'dailymotion',
    addedAt: '2026-03-08T09:30:00.000Z',
    isFavorite: false,
  },
  'v-nature-05': {
    id: 'v-nature-05',
    url: 'https://www.youtube.com/watch?v=LXb3EKWsInQ',
    title: 'Norvège — Aurores boréales en time-lapse',
    thumbnail: 'https://img.youtube.com/vi/LXb3EKWsInQ/hqdefault.jpg',
    duration: 630,
    source: 'youtube',
    addedAt: '2026-03-12T20:00:00.000Z',
    isFavorite: false,
  },

  // — Musique playlist
  'v-music-01': {
    id: 'v-music-01',
    url: 'https://www.youtube.com/watch?v=kXYiU_JCYtU',
    title: 'Nils Frahm — All Melody (Live at Sydney Opera House)',
    thumbnail: 'https://img.youtube.com/vi/kXYiU_JCYtU/hqdefault.jpg',
    duration: 4560,
    source: 'youtube',
    addedAt: '2026-03-02T19:00:00.000Z',
    isFavorite: true,
  },
  'v-music-02': {
    id: 'v-music-02',
    url: 'https://vimeo.com/104297054',
    title: 'Ólafur Arnalds — Near Light (Session vidéo)',
    thumbnail: 'https://i.vimeocdn.com/video/488843836_640.jpg',
    duration: 378,
    source: 'vimeo',
    addedAt: '2026-03-09T21:00:00.000Z',
    isFavorite: false,
  },
  'v-music-03': {
    id: 'v-music-03',
    url: 'https://www.dailymotion.com/video/x2yhql3',
    title: 'Bonobo — Kiara (Live at Printworks)',
    thumbnail: 'https://s2.dmcdn.net/v/Sm2ij1Y4Whg3J7A2F/x720',
    duration: 1140,
    source: 'dailymotion',
    addedAt: '2026-03-11T18:00:00.000Z',
    isFavorite: true,
  },
  'v-music-04': {
    id: 'v-music-04',
    url: 'https://www.youtube.com/watch?v=6QL0Hbz1Aqo',
    title: 'Floating Points — Crush (Full Album Stream)',
    thumbnail: 'https://img.youtube.com/vi/6QL0Hbz1Aqo/hqdefault.jpg',
    duration: 2700,
    source: 'youtube',
    addedAt: '2026-03-14T20:30:00.000Z',
    isFavorite: false,
  },
};

export const seedPlaylists: Record<string, Playlist> = {
  'pl-tech': {
    id: 'pl-tech',
    name: 'Tech Talks',
    description: 'Conférences et tutoriels sur le développement web et mobile',
    category: 'Technologie',
    videoIds: ['v-tech-01', 'v-tech-02', 'v-tech-03', 'v-tech-04', 'v-tech-05'],
    viewMode: 'list',
    createdAt: '2026-03-01T09:00:00.000Z',
    coverImage: 'https://img.youtube.com/vi/dQw4w9WgXcQ/hqdefault.jpg',
  },
  'pl-nature': {
    id: 'pl-nature',
    name: 'Nature & Voyages',
    description: 'Documentaires et films de voyage autour du monde',
    category: 'Voyage',
    videoIds: ['v-nature-01', 'v-nature-02', 'v-nature-03', 'v-nature-04', 'v-nature-05'],
    viewMode: 'stack',
    createdAt: '2026-03-03T07:00:00.000Z',
    coverImage: 'https://i.vimeocdn.com/video/560965144_640.jpg',
  },
  'pl-music': {
    id: 'pl-music',
    name: 'Musique',
    description: 'Sessions live et concerts de musique électronique et ambiante',
    category: 'Musique',
    videoIds: ['v-music-01', 'v-music-02', 'v-music-03', 'v-music-04'],
    viewMode: 'list',
    createdAt: '2026-03-02T18:00:00.000Z',
    coverImage: 'https://img.youtube.com/vi/kXYiU_JCYtU/hqdefault.jpg',
  },
};
